version: '3.8'

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: qodrexpense
    ports:
      - "5432:5432"
    volumes:
      - ./lib/postgresql/data:/var/lib/postgresql/data

volumes:
  db_data:
